default_config = {
    "Controller": {
        "Up":                           [None, None],
        "Down":                         [None, None],
        "Strafe Left":                  [None, None],
        "Strafe Right":                 [None, None],
        "Forward":                      [None, None],
        "Backward":                     [None, None],
        "Yaw Left":                     [None, None],
        "Yaw Right":                    [None, None],
        "Pitch Up":                     [None, None],
        "Pitch Down":                   [None, None],
        "Roll Left":                    [None, None],
        "Roll Right":                   [None, None],
        "Diagonal Strafe Left Forward": [None, None],
        "Diagonal Strafe Right Forward":[None, None],
        "Arm Open":                     [None, None],
        "Arm Close":                    [None, None],
        "Arm Move Forward":             [None, None],
        "Arm Move Backward":            [None, None],
        "Stop All":                     [None, None],
    },
    "Keyboard": {
        "Up":                           [None, None],
        "Down":                         [None, None],
        "Strafe Left":                  [None, None],
        "Strafe Right":                 [None, None],
        "Forward":                      [None, None],
        "Backward":                     [None, None],
        "Yaw Left":                     [None, None],
        "Yaw Right":                    [None, None],
        "Pitch Up":                     [None, None],
        "Pitch Down":                   [None, None],
        "Roll Left":                    [None, None],
        "Roll Right":                   [None, None],
        "Diagonal Strafe Left Forward": [None, None],
        "Diagonal Strafe Right Forward":[None, None],
        "Arm Open":                     [None, None],
        "Arm Close":                    [None, None],
        "Arm Move Forward":             [None, None],
        "Arm Move Backward":            [None, None],
        "Stop All":                     [None, None],
    }
}