default_config  = {
    "Up":,
    "Down":,
    "Strafe Left":,
    "Strafe Right":,
    "Forward":,
    "Backward":,
    "Yaw Left":,
    "Yaw Right":,
    "Pitch Up":,
    "Pitch Down":,
    "Roll Left":,
    "Roll Right":,
    "Diagonal Strafe Left Forward":,
    "Diagonal Strafe Right Forward":,
    "Arm Open":,
    "Arm Close":,
    "Arm Move Forward":,
    "Arm Move Backward":,
    "Stop All":,
    }